### ISSUE TITLE
Autenticação para anúncio de vagas

### ISSUE THREAD

**Issue by filipechagas** [matheusml/rubyjobs#55]
Hoje postei uma vaga no site e e percebi que a descrição não ficou boa. Gostaria de ser capaz de editar, mas infelizmente isso não é atualmente possível.

Uma autenticação básica (não-obrigatória) pra postagem de vagas seria interessante.

Estou disposto a implementar e enviar o pull-request, mas gostaria de saber se a feature vai ser aceita antes de implementar.

**Comment by gfvcastro** [comment]
Me gusta esta idea. Estoy dispuesto a colaborar en esta funcionaidad.

**Comment by matheusml** [comment]
@gfvcastro you can do it.

**Comment by guvarallo** [comment]
Remoção de anúncios seria uma outra issue ou estaria atrelada à essa? Me parece importante os criadores serem capazes de deletar o anúncio. Para os que não teriam cadastro, então disponibilizar um canal para solicitar a remoção. E para todos os anúncios uma data de validade? 60 dias? Creio que tira um pouco a credibilidade do site ter anúncios muito antigos.

**Comment by Brunozrk** [comment]
Com relação a anúncios antigos podemos colocar um filtro na busca para trazer só os mais recentes.

Com relação a cadastro e tal, como disse o @matheusml https://github.com/matheusml/rubyjobs/issues/55#issuecomment-63640431, é importante deixar claro no layout.

Acho bacana isso, mas temos que evoluir a ideia!

**Comment by matheusml** [comment]
@guvarallo a data de validade deles é de três meses. Se não me engano existe essa observação na criação de um Job novo.

**Comment by esasse** [comment]
Algumas sugestões que podem (ou não) ajudar a evoluir a ideia:
- Ao cadastrar a vaga, o usuário tem a sessão dele ainda criada e poderia editar a vaga sem problemas, pois sabemos que foi ele que cadastrou.
- Gerar automaticamente uma senha por vaga e enviar por e-mail ao usuário que cadastrou. Ele usaria a senha de cada vaga para editar. O legal disso é que fica bem mais simples do que criar cadastros de usuários, etc.

**Comment by matheusml** [comment]
@esasse gostei muito da ideia, só temos dois problemas:
1. Encontrar uma forma gratuita de enviar e-mails, lembrando que estamos no **heroku**, então talvez uma ferramenta como **SendGrid** ou **MailChimp** ofereça algum plano gratuito para opensource ou então para pouco envio de e-mails.
O outro problema.
2. Encontrar uma forma gratuita de ter um email do tipo xxx@rubyjobs.me, não seria muito interessante para as empresas receberam emails xxx@gmail.com.

**Comment by esasse** [comment]
1. [Mandrill](http://mandrill.com/) permite até 12k e-mails gratuitos por mês.
2. Isso acho que não é problema. Você pode mandar de um endereço qualquer sem existir uma caixa de e-mail no endereço. Os noreply@xxx por exemplo, não existem, não são endereços válidos.

Além disso, assim que o usuário cadastrar a vaga, também podemos mostrar a senha na tela e avisar para ele anotar caso queira editar a vaga depois.
