### ISSUE TITLE
Permitir apontar para uma URL ao invés de um e-mail

### ISSUE THREAD

**Issue by esasse** [matheusml/rubyjobs#70]
Nosso processo de seleção requer que os candidatos preencham um formulário, então quando entram em contato comigo pelo e-mail que coloquei no anúncio, sempre tenho que dar a mesma resposta pedindo para preencherem o formulário para participarem do processo.

Ou seja, seria interessante que pudessemos especificar direto uma URL para quem gostou da vaga e opcionalmente também um e-mail.

**Comment by matheusml** [comment]
Acho válido, diversas empresas de fato tem uma página só para isso. 
Só acho que o e-mail deveria continuar obrigatório.

**Comment by esasse** [comment]
Mas por que não deixar isso a critério do usuário? Claro que ele não poderia deixar os dois em branco. Seria obrigatório pelo menos uma forma de obter mais informações da vaga.

O que nós percebemos é que quando tem um e-mail publicado na vaga, muita gente não segue o processo de preencher o formulário e só faz todo mundo perder tempo, pois ao enviar o e-mail, ele é instruído a preencher o formulário se quiser participar do processo.

**Comment by matheusml** [comment]
A necessidade de ter um e-mail é pra ter um "responsável" pela vaga.
Alguém para contato direto caso a página esteja com algum problema, ou mesmo dúvidas em geral.
Além disso, pelo que foi discutido na #55 assim que o usuário criar um job novo, ele irá receber um e-mail.

**Comment by esasse** [comment]
Sim, com certeza. Eu deveria ter sido mais claro. A publicação do e-mail na página da vaga acho que poderia ser opcional.

**Comment by Brunozrk** [comment]
Acho que email deve ser obrigatório e fica a cargo do usuário escolher se deve aparecer na vaga ou não.
Algo como:

Cadastrou só email (o email vai aparecer)
Cadastrou email e link com formulário (o usuário escolhe se o email deve ou não aparecer junto com o link)

É isso @esasse?

**Comment by esasse** [comment]
É isso, porém agora lendo a regra de que ele só vai ter a opção de ocultar o e-mail no caso de ele ter cadastrado também a URL, acho que vai complicar um pouco a interface. :(

Acho que tive uma ideia melhor. Ao cadastrar a vaga, você tem a opção de escolher a forma de contato para os interessados em se candidatar:
- E-mail (neste caso não precisa fazer nada, já fica como está)
- Link (neste caso, mostramos o campo para preencher o link e ele automaticamente se torna obrigatório. Neste caso também o e-mail fica automaticamente oculto da página da vaga)

Acho que assim ficaria simples e resolveria o problema. O que acham?

**Comment by matheusml** [comment]
@esasse essa última parece a ideal.

**Comment by esasse** [comment]
Eu me disponho a trabalhar nisso se quiser.

**Comment by Brunozrk** [comment]
:+1:

**Comment by matheusml** [comment]
Show!
