### ISSUE TITLE
Admin para validar anúncios

### ISSUE THREAD

**Issue by Brunozrk** [matheusml/rubyjobs#78]
O que acham de criarmos um admin para validarmos os anúncios?

Assim evitamos cadastros como estes:

http://www.rubyjobs.me/jobs/76-desenvolvedor-ruby-on-rails
http://www.rubyjobs.me/jobs/75-ruby-on-rails

O [ActiveAdmin](https://github.com/activeadmin/activeadmin) pode ajudar, rsrs

O que acham?

**Comment by emaiax** [comment]
:+1:

**Comment by lucasnogueira** [comment]
Concordo, visto que parece que a galera está curtindo fazer uns cadastros
assim agora.

2015-01-21 12:36 GMT-02:00 Eduardo Maia <notifications@github.com>:

**Comment by matheusml** [comment]
Pensei que já tinham parado de fazer isso.
A princípio eu acho que não vale a pena pelo seguinte:
1) O gestor cria o job
2) Ele é mandado para a página do job criado na mesma hora
3) Ele pode compartilhar o job (o que aumenta muito as visitas no site)

Se a gente põe essa barreira de entrada, a gente vai praticamente matar os shares por facebook.
Opiniões?

**Comment by Brunozrk** [comment]
2) Ele é mandado para a página do job criado na mesma hora
  - Nesse caso podemos apenas enviar para uma página informando ao usuário que a vaga será analisada.

3) Ele pode compartilhar o job (o que aumenta muito as visitas no site)
  - É, nesse caso seria só depois da aprovação.

Entendi os casos, mas não é melhor manter a credibilidade do site sem vagas fake?

Acho que temos que pensar em algo para impedir isso sem perder essas features que vc citou!

**Comment by matheusml** [comment]
Também acho as fakes bem ruins, o lance é que são raras de acontecer comparadas com as de verdade. Acho que vale a pena pensarmos em alguma forma que consiga alinhar as duas, mas infelizmente a proposta não vai dar.

**Comment by Brunozrk** [comment]
Ok, vamos ver se continuam...
