### ISSUE TITLE
Data para expiração para a vaga

### ISSUE THREAD

**Issue by luizpicolo** [matheusml/rubyjobs#79]
Seria interessante uma data limite para as vagas, ou seja, não necessáriamente todas as vagas seriam mostras no site, mas somente as que tiveram sua data limite válida.

**Comment by brunozrk** [comment]
@luizpicolo, o projeto agora esta em
https://github.com/ruby-jobs/ruby-jobs

**Comment by luizpicolo** [comment]
Thanks. :+1:
