### ISSUE TITLE
Pensar numa forma de evitar SPAM?

### ISSUE THREAD

**Issue by esasse** [matheusml/rubyjobs#80]
Ontem recebi um SPAM que provavelmente veio do RubyJobs, pois todos os endereços de e-mail ficam expostos e podem ser usados para qualquer fim.

![image](https://cloud.githubusercontent.com/assets/148989/7047311/17f4109c-dde2-11e4-8cb1-39caacc45e48.png)

A primeira ideia que eu tive foi criar um formulário para os candidatos preencherem, que seria direcionado automaticamente para o e-mail da vaga, mas também não resolve muito, pois esse cidadão poderia ter preenchido o formulário com o mesmo conteúdo. :disappointed:

Acham que vale a pena pensar em algo?

**Comment by matheusml** [comment]
Não consigo pensar em nenhuma solução viável pra isso.
A maioria dos sites de postagem de Jobs tem o e-mail exposto da empresa, justamente pra comunicação entre empresa-candidato ficar livre.

**Comment by esasse** [comment]
É, também não tenho nenhuma ideia que resolva. Vou fechar a issue então. Se alguém tiver uma ideia, reabre.
